### ISSUE TITLE
Error: failed to restore

### ISSUE THREAD

**Issue by hissssst** [nix-community/cache-nix-action#9] opened 2023-08-01 17:53 UTC
Whole restore step is filled with errors like this. Action is set up just like in example in the docs

```
/usr/bin/tar: ../../../../../nix/store/h5c0n2pcidaikpm6pwm8v9hz81ndmppj-aws-sdk-cpp-1.11.37/lib/libtesting-resources.so: Cannot open: File exists
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Failed to restore: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2
Cache not found for input keys: nix-f69b52731a4e03acd9238e5c4b0e1db653f46d92e3a380bab33c5ab7c53f0155, nix-f69b52731a4e03acd9238e5c4b0e1db653f46d92e3a380bab33c5ab7c53f0155
```

Doc says that it's okay, but my `nix develop` command still downloads all the packages

**Comment by hissssst** [comment] 2023-08-02 14:48
@deemp ping

**Comment by deemp** [comment] 2023-08-03 11:22
@hissssst, I'm traveling. Please, share a link to your repo. If you can't, please, try to reproduce this problem in another repo.

**Comment by deemp** [comment] 2023-08-06 14:45
I'll close this issue until there's more context.

**Comment by hissssst** [comment] 2023-08-06 18:51
@deemp reopen it please and do not close it unless significant time passes or we resolve the issue. You can't just close an issue if someone didn't respond during the weekend

**Comment by deemp** [comment] 2023-08-06 20:10
@hissssst, I didn't know about this GH feature.

> you cannot re-open your own issues if a repo collaborator closed them.

I expected that you'll re-open this issue when you can provide more context.

I'll re-open the issue.

**Comment by hissssst** [comment] 2023-08-16 16:20
@deemp I've created open source project where this error is reproduced
https://github.com/hissssst/nebulex_adapters_ecto

**Comment by hissssst** [comment] 2023-08-31 15:04
@deemp this action didn't help in my private project. The same error persists

**Comment by deemp** [comment] 2023-08-31 21:24
How did you check it's not your error? BTW, I integrated `purge-cache` into `cache-nix-action`. See https://github.com/nix-community/cache-nix-action#purge-old-caches

**Comment by deemp** [comment] 2023-08-31 21:28
If you try the latest version, please, provide the logs of `cache-nix-action` (the first and the post phases).

**Comment by deemp** [comment] 2023-12-28 16:14
@hissssst, now, there's usually no overwriting due to `--skip-old-files`

https://github.com/nix-community/cache-nix-action/blame/317362693c54649457bbaa0e5fe20df5f6c638ec/src/utils/action.ts#L79

A tar command looks like this

```console
/usr/local/bin/gtar -xf /Users/runner/work/_temp/692c618e-65d6-4229-a8d8-7c11ee882599/cache.tzst -P -C /Users/runner/work/cache-nix-action/cache-nix-action --delay-directory-restore --skip-old-files --use-compress-program unzstd
```

However, errors occur sometimes on macOS (see https://github.com/nix-community/cache-nix-action/issues/24)

**Comment by deemp** [comment] 2024-03-31 07:04
Currently, existing `/nix/store` paths are skipped when restoring a cache ([link](https://github.com/nix-community/cache-nix-action/blob/2dcc42ae696ebf2f53e6ad1409bc7e801ba072cb/src/utils/action.ts#L84-L95)).

**Comment by deemp** [comment] 2024-04-06 05:03
@hissssst, I made several releases since September. They may have solved your problem, so I'm closing this issue. Feel free to create new issues if there are any problems with `cache-nix-action`.

**Closed by deemp** 2024-04-06 05:03 UTC
